projects:
  amplify:
    schemaPath: src\graphql\schema.json
    includes:
      - src\graphql\**\*.graphql
    excludes:
      - ./amplify/**
    extensions:
      amplify:
        codeGenTarget: angular
        generatedFileName: src\app\API.service.ts
        docsFilePath: src\graphql
        graphQLApiId: aqqj2flobrddpbnt2lct6hpzda
      endpoints:
        prod: >-
          https://uxzcv2buzjhkvf5cwxu7evb7g4.appsync-api.us-east-1.amazonaws.com/graphql
